'use client';
import dynamic from 'next/dynamic';import Link from 'next/link';import { useEffect,useState } from 'react';import { usePathname,useSearchParams } from 'next/navigation';import { AnimatePresence,motion } from 'framer-motion';
import { ArrowLeft,ArrowUpRight,ChevronRight,ChevronDown,Compass,Eye,Info,Maximize,Minus,Orbit,Plus,RotateCcw,SlidersHorizontal,X } from 'lucide-react';
import { providers,models,families,getProvider,getModel,getFamily,providerModels } from '@/data/catalog';import { useUniverse } from '@/store/universe';import { parseSelection,selectionUrl } from '@/lib/catalog';import { chooseQuality } from '@/lib/scene-layout';import { track } from '@/lib/analytics';
import ModelDetails from './ui/ModelDetails';import SceneBoundary,{Fallback} from './ui/SceneBoundary';import type {Quality} from '@/types/catalog';
const Scene=dynamic(()=>import('./three/UniverseScene'),{ssr:false,loading:()=> <div className="scene-loading"><Orbit size={30}/><span>Initializing Universe…</span><div className="loading-track"/></div>});
export default function Explorer(){const s=useUniverse();const params=useSearchParams(),path=usePathname();const [settings,setSettings]=useState(false),[help,setHelp]=useState(false),[error,setError]=useState(''),[fps,setFps]=useState<number|null>(null);const provider=s.selection.provider?getProvider(s.selection.provider):null,model=s.selection.model?getModel(s.selection.model):null,family=s.selection.family?getFamily(s.selection.family):null;
 useEffect(()=>{const media=matchMedia('(prefers-reduced-motion: reduce)');const reduce=()=>useUniverse.setState({reducedMotion:media.matches});reduce();media.addEventListener('change',reduce);const memory=(navigator as Navigator&{deviceMemory?:number}).deviceMemory;s.setQuality(chooseQuality(innerWidth,memory,devicePixelRatio),true);const canvas=document.createElement('canvas');const gl=canvas.getContext('webgl2')||canvas.getContext('webgl');if(!gl){useUniverse.setState({fallback:true});track('fallback_used',{reason:'webgl-unavailable'});}else gl.getExtension('WEBGL_lose_context')?.loseContext();try{if(localStorage.getItem('ai-universe-entered'))useUniverse.setState({entered:true});}catch{}if(path.startsWith('/explore'))useUniverse.setState({entered:true});return()=>media.removeEventListener('change',reduce);
 // Setup happens once on entry; subsequent choices are controlled by the user.
 // eslint-disable-next-line react-hooks/exhaustive-deps
 },[]);
 useEffect(()=>{const selection=parseSelection(params);if(params.has('model')&&!selection.model)setError('This model could not be found. Showing the universe.');else if(params.has('provider')&&!selection.provider)setError('This provider could not be found. Showing the universe.');else setError('');if(JSON.stringify(selection)!==JSON.stringify(useUniverse.getState().selection))s.select(selection);
 // eslint-disable-next-line react-hooks/exhaustive-deps
 },[params]);
 useEffect(()=>{const unsubscribe=useUniverse.subscribe((next,prev)=>{if(next.selection!==prev.selection){window.history.replaceState(null,'',selectionUrl(next.selection));}});const back=(e:KeyboardEvent)=>{if(e.key==='Escape'&&!useUniverse.getState().searchOpen){if(settings)setSettings(false);else if(help)setHelp(false);else useUniverse.getState().back();}};const perf=(e:Event)=>setFps((e as CustomEvent).detail.fps);window.addEventListener('keydown',back);window.addEventListener('universe:performance',perf);return()=>{unsubscribe();window.removeEventListener('keydown',back);window.removeEventListener('universe:performance',perf);};},[settings,help]);
 return <main id="main" className="explorer"><div className="scene-container" aria-label="Interactive 3D map of AI providers"><SceneBoundary>{s.fallback?<Fallback/>:<Scene/>}</SceneBoundary></div><div className="scene-vignette"/>
 <div className="explore-heading"><div className="eyebrow"><span className="tiny-line"/> AN ATLAS OF ARTIFICIAL INTELLIGENCE</div><h1>{provider?provider.name:<>Intelligence. <span>Interconnected.</span></>}</h1><p>{provider?provider.description:'Explore the models, minds, and possibilities shaping our world.'}</p></div>
 <nav className="breadcrumb" aria-label="Universe hierarchy"><button onClick={s.reset}><Compass size={14}/>Universe</button>{provider&&<><ChevronRight size={13}/><button onClick={()=>s.select({provider:provider.id})}>{provider.name}</button></>}{family&&<><ChevronRight size={13}/><button onClick={()=>s.select({provider:provider!.id,family:family.id})}>{family.name}</button></>}{model&&<><ChevronRight size={13}/><span>{model.name}</span></>}</nav>
 <aside className="provider-rail" aria-label="Explore providers"><div className="rail-heading">{provider?'IN THIS GALAXY':'PROVIDER GALAXIES'}<span>{provider?providerModels(provider.id).length.toString().padStart(2,'0'):providers.length.toString().padStart(2,'0')}</span></div>{provider?<><button className="back-button" onClick={s.back}><ArrowLeft size={14}/> {family?'Back to '+provider.name:'All providers'}</button>{!family?families.filter(f=>f.providerId===provider.id).map(f=><button key={f.id} className="provider-row" onClick={()=>s.select({provider:provider.id,family:f.id})}><Orbit size={17}/><span>{f.name}<small>Model family</small></span><ChevronRight size={14}/></button>):providerModels(provider.id).filter(m=>m.familyId===family.id).map(m=><button key={m.id} className={`provider-row ${model?.id===m.id?'active':''}`} onClick={()=>s.select({provider:provider.id,family:family.id,model:m.id})}><span className="provider-dot" style={{background:provider.color}}/><span>{m.name}<small>{m.capabilities.slice(0,2).join(' · ')}</small></span><ChevronRight size={14}/></button>)}<Link className="rail-link" href={`/providers/${provider.slug}`}>Provider profile<ArrowUpRight size={14}/></Link></>:providers.map((p,i)=><button key={p.id} className="provider-row" onClick={()=>s.select({provider:p.id})}><span className="provider-index">{String(i+1).padStart(2,'0')}</span><span className="provider-dot" style={{background:p.color}}/><span>{p.name}</span><ChevronRight size={13}/></button>)}<div className="rail-note"><span className="pulse-dot"/> {models.length} models. One connected universe.</div></aside>
 {!s.entered&&!s.fallback&&<motion.div className="intro-card" initial={{opacity:0,y:8}} animate={{opacity:1,y:0}}><span className="eyebrow">WELCOME TO THE OBSERVATORY</span><h2>Follow your curiosity.</h2><p>Explore the intelligence shaping our world.</p><button className="primary-button" onClick={s.enter}>Explore Universe <ArrowUpRight size={17}/></button></motion.div>}
 {s.entered&&!provider&&!s.fallback&&<div className="explore-invitation"><span className="orbital-symbol"><Orbit size={20} strokeWidth={1}/></span><span>Every point is a possibility.<small>Select a galaxy to begin exploring.</small></span></div>}
 <AnimatePresence>{model&&<motion.aside key={model.id} className="detail-panel" initial={{opacity:0,x:s.reducedMotion?0:20}} animate={{opacity:1,x:0}} exit={{opacity:0}} aria-label={`${model.name} details`}><div className="panel-toolbar"><span>MODEL OBSERVATORY</span><button className="icon-button" aria-label="Close model details" onClick={s.back}><X size={18}/></button></div><ModelDetails model={model}/></motion.aside>}</AnimatePresence>
 {error&&<div className="toast" role="alert">{error}<button aria-label="Dismiss message" onClick={()=>setError('')}><X size={16}/></button></div>}
 <div className="scene-tools"><button className="icon-button" aria-label="Zoom in" onClick={()=>window.dispatchEvent(new CustomEvent('universe:zoom',{detail:.8}))}><Plus size={18}/></button><button className="icon-button" aria-label="Zoom out" onClick={()=>window.dispatchEvent(new CustomEvent('universe:zoom',{detail:1.25}))}><Minus size={18}/></button><span className="tool-divider"/><button className="icon-button" aria-label="Reset view" onClick={s.reset}><RotateCcw size={17}/></button><button className="icon-button" aria-label="Toggle object labels" aria-pressed={s.labels} onClick={()=>useUniverse.setState({labels:!s.labels})}><Eye size={17}/></button><button className="icon-button" aria-label="Toggle fullscreen" onClick={async()=>{try{if(document.fullscreenElement)await document.exitFullscreen();else await document.documentElement.requestFullscreen();}catch{setError('Fullscreen is not available in this browser.')}}}><Maximize size={16}/></button></div>
 <footer className="explore-footer"><div className="view-indicator"><Orbit size={15}/><span>{model?'Model focus':family?'Family system':provider?'Provider galaxy':'Universe view'}</span><span className="footer-divider"/><span className="coordinates">{provider?provider.id.toUpperCase():'ALL SYSTEMS'}</span></div><div className="control-hints"><span>Drag to orbit</span><i>·</i><span>Scroll to zoom</span><i>·</i><span>Click to explore</span></div><div className="quality-control"><button className="quality-button" onClick={()=>setSettings(!settings)} aria-expanded={settings}><span className="quality-bars">▂▄▆</span>{s.autoQuality?'Auto · ':''}{s.quality.toLowerCase()}<ChevronDown size={13}/></button><button className="icon-button" aria-label="Navigation help" aria-expanded={help} onClick={()=>setHelp(!help)}><Info size={17}/></button></div></footer>
 {settings&&<section className="settings-popover" aria-label="Display settings"><div className="popover-heading"><SlidersHorizontal size={17}/><h2>Display settings</h2></div><label>Rendering quality<select aria-label="Rendering quality" value={s.autoQuality?'AUTO':s.quality} onChange={e=>e.target.value==='AUTO'?s.setQuality(chooseQuality(innerWidth,undefined,devicePixelRatio),true):s.setQuality(e.target.value as Quality)}><option value="AUTO">Auto (recommended)</option><option value="LOW">Low</option><option value="MEDIUM">Medium</option><option value="HIGH">High</option></select></label><label className="checkbox-label"><input type="checkbox" checked={s.reducedMotion} onChange={e=>useUniverse.setState({reducedMotion:e.target.checked})}/>Reduce motion</label><label className="checkbox-label"><input type="checkbox" checked={s.fallback} onChange={e=>useUniverse.setState({fallback:e.target.checked})}/>Use accessible 2D view</label><small>{fps?`Measured frame rate: ${fps} FPS`:'Measuring scene performance…'}</small></section>}
 {help&&<section className="help-popover" aria-label="Navigation help"><h2>Find your way</h2><p>Drag to orbit. Scroll or pinch to zoom. Select a provider, then a family and model.</p><p><kbd>Esc</kbd> moves up one level. <kbd>⌘ / Ctrl K</kbd> opens search.</p><Link href="/models">Prefer a list? Browse all models →</Link></section>}
 </main>;
}
